name: Deploy to EvenNode

on:
  push:
    branches:
      - master
      - editorial_workflow

permissions:
  contents: read
  deployments: write

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - uses: chrnorm/deployment-action@v2
        name: Create Evennode deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: http://quemeimporta.eu-4.evennode.com/
          environment: evennode

      - name: EvenNode Deploy
        uses: rodnye/evennode-deploy-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          git_url: ${{ secrets.EVENNODE_REPO_URL }}
          pre_commit_command: |
            git reset .
            npm install
            npm run blog:sync
            npm run build
            git add -f dist package.json package-lock.json

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
