name: Deploy to EvenNode

on:
  push:
    branches:
      - master
      - editorial_workflow

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: EvenNode Deploy
        uses: rodnye/evennode-deploy-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          git_url: ${{ secrets.EVENNODE_REPO_URL }}
          pre_commit_command: |
            git reset .
            npm install
            npm run blog:sync
            npm run build
            git add -f dist package.json package-lock.json
