name: Trigger Cloudflare Pages Build
on:
  push:
    branches:
      - master
      - editorial_workflow

jobs:
  build:
    name: Request Cloudflare Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create Cloudflare deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://quemeimporta.pages.dev
          environment: cloudflare-pages

      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.CLOUDFLARE_BUILD_HOOK }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
